/**
 * Complete Algerian administrative dataset: 69 wilayas and 1,541 communes.
 * Source: Algeria Law 26-06 / Journal Officiel No. 25 (5 April 2026).
 * Each entry: [code, nameAr, nameFr, nameEn, deliveryFee(DZD), etaDays, communes[]]
 * Commune entries are "Arabic|French"; the English name defaults to the French one.
 */
export type WilayaSeed = {
  code: string;
  nameAr: string;
  nameFr: string;
  nameEn: string;
  fee: number;
  eta: string;
  communes: { nameAr: string; nameFr: string; nameEn: string }[];
};

type Raw = [string, string, string, string, number, string, string[]];

const RAW: Raw[] = [
  ["01", "أدرار", "Adrar", "Adrar", 1200, "5-8", ["تيمقتن|Timekten", "تيت|Tit", "اقبلي|Akabli", "أولف|Aoulef", "بودة|Bouda", "أولاد أحمد تيمي|Ouled Ahmed Timmi", "أدرار|Adrar", "فنوغيل|Fenoughil", "تامست|Tamest", "تامنطيط|Tamantit", "إن زغمير|In Zghmir", "زاوية كنتة|Zaouiet Kounta", "رقان|Reggane", "سالي|Sali", "السبع|Sebaa", "تسابيت|Tsabit"]],
  ["02", "الشلف", "Chlef", "Chlef", 700, "3-5", ["تلعصة|Talassa", "تاجنة|Tadjena", "أبو الحسن|Abou El Hassane", "الزبوجة|Zeboudja", "بوزغاية|Bouzeghaia", "بنايرية|Benairia", "الحجاج|El Hadjadj", "أولاد بن عبد القادر|Ouled Ben Abdelkader", "عين مران|Ain Merane", "الهرانفة|Herenfa", "بريرة|Breira", "بني حواء|Beni Haoua", "وادي قوسين|Oued Goussine", "أولاد عباس|Ouled Abbes", "وادي الفضة|Oued Fodda", "بني راشد|Beni Rached", "المرسى|El Marsa", "مصدق|Moussadek", "الشلف|Chlef", "أم الدروع|Oum Drou", "سنجاس|Sendjas", "سيدي عبد الرحمن|Sidi Abderrahmane", "سيدي عكاشة|Sidi Akkacha", "تنس|Tenes", "بني بوعتاب|Beni  Bouattab", "الكريمية|El Karimia", "حرشون|Harchoun", "تاوقريت|Taougrit", "الظهرة|Dahra", "الشطية|Chettia", "أولاد فارس|Ouled Fares", "الأبيض مجاجة|Labiod Medjadja", "بوقادير|Boukadir", "وادي سلي|Oued Sly", "الصبحة|Sobha"]],
  ["03", "الأغواط", "Laghouat", "Laghouat", 900, "4-7", ["تاجموت|Tadjemout", "تاجرونة|Tadjrouna", "عين ماضي|Ain Madhi", "الحويطة|El Haouita", "الخنق|Kheneg", "الأغواط|Laghouat", "قصر الحيران|Ksar El Hirane", "بن ناصر بن شهرة|Benacer Benchohra", "العسافية|El Assafia", "سيدي مخلوف|Sidi Makhlouf", "حاسي الدلاعة|Hassi Delaa", "حاسي الرمل|Hassi R’Mel"]],
  ["04", "أم البواقي", "Oum El Bouaghi", "Oum El Bouaghi", 700, "3-5", ["فكيرينة|Fkirina", "وادي نيني|Oued Nini", "الفجوج بوغرارة سعودي|El Fedjoudj Boughrara Sa", "عين فكرون|Ain Fekroun", "الرحية|Rahia", "مسكيانة|Meskiana", "البلالة|El Belala", "بحير الشرقي|Behir Chergui", "قصر الصباحي|Ksar Sbahi", "سوق نعمان|Souk Naamane", "أولاد زواي|Ouled Zouai", "بئر الشهداء|Bir Chouhada", "أم البواقي|Oum El Bouaghi", "عين الزيتون|Ain Zitoun", "عين ببوش|Ain Babouche", "عين الديس|Ain Diss", "عين البيضاء|Ain Beida", "بريش|Berriche", "الزرق|Zorg", "عين مليلة|Ain M'lila", "أولاد قاسم|Ouled Gacem", "أولاد حملة|Ouled Hamla", "العامرية|El Amiria", "سيقوس|Sigus", "الضلعة|Dhalaa", "الجازية|El Djazia", "عين كرشة|Ain Kercha", "الحرملية|El Harmilia", "هنشير تومغني|Hanchir Toumghani"]],
  ["05", "باتنة", "Batna", "Batna", 700, "3-5", ["معافة|Maafa", "عين التوتة|Ain Touta", "بني فضالة الحقانية|Beni Fedhala El Hakania", "أولاد عوف|Ouled Aouf", "القصبات|Gosbat", "تالخمت|Talkhamt", "رأس العيون|Ras El Aioun", "الرحبات|Rahbat", "أولاد سلام|Ouled Sellem", "القيقبة|Guigba", "تيمقاد|Timgad", "أولاد فاضل|Ouled Fadel", "تاكسلانت|Taxlent", "أولاد سي سليمان|Ouled Si Slimane", "لمسان|Lemsane", "ثنية العابد|Teniet El Abed", "شير|Chir", "وادي الطاقة|Oued Taga", "باتنة|Batna", "فسديس|Fesdis", "وادي الشعبة|Oued Chaaba", "حيدوسة|Hidoussa", "قصر بلزمة|Ksar Belezma", "مروانة|Merouana", "وادي الماء|Oued El Ma", "لازرو|Lazrou", "سريانة|Seriana", "زانة البيضاء|Zana El Beida", "منعة|Menaa", "تغرغار|Tigherghar", "عين ياقوت|Ain Yagout", "بومية|Boumia", "جرمة|Djerma", "المعذر|Elmadher", "عيون العصافير|Ouyoun El Assafir", "تازولت|Tazoult", "بومقر|Boumagueur", "نقاوس|N’Gaous", "سفيان|Sefiane", "أريس|Arris", "تيغانمين|Tighanimine", "عين جاسر|Ain Djasser", "الحاسي|El Hassi", "فم الطوب|Foum Toub", "إشمول|Ichmoul", "إينوغيسن|Inoughissene", "بوزينة|Bouzina", "لارباع|Larbaa", "بولهيلات|Boulhilat", "الشمرة|Chemora", "غسيرة|Ghassira", "كيمل|Kimmel", "تكوت|T’Kout"]],
  ["06", "بجاية", "Bejaia", "Bejaia", 650, "2-4", ["سيدي عياد|Sidi Ayad", "الفلاي|Leflaye", "سيدي عيش|Sidi-Aich", "تيفرة|Tifra", "تينبدار|Tinebdar", "برباشة|Barbacha", "كنديرة|Kendira", "القصر|El Kseur", "فناية الماثن|Fenaia Il Maten", "توجة|Toudja", "ذراع القايد|Dra El Caid", "خراطة|Kherrata", "بجاية|Bejaia", "وادي غير|Oued Ghir", "بني معوش|Benimaouche", "بني جليل|Beni Djellil", "فرعون|Feraoun", "سمعون|Smaoun", "أميزور|Amizour", "تيمزريت|Timezrit", "مالبو|Melbou", "سوق لإثنين|Souk El Tenine", "تامريجت|Tamridjet", "بوخليفة|Boukhelifa", "تالة حمزة|Tala Hamza", "تيشي|Tichy", "أيت رزين|Ait R'zine", "إغيل علي|Ighil-Ali", "أيت إسماعيل|Ait-Smail", "درقينة|Darguina", "تاسكريوت|Taskriout", "أوقاس|Aokas", "تيزي نبربر|Tizi-N'berber", "أدكار|Adekar", "بني كسيلة|Beni K'sila", "تاوريرت إغيل|Taourit Ighil", "أقبو|Akbou", "شلاطة|Chellata", "اغرم|Ighram", "تامقرة|Tamokra", "أمالو|Amalou", "بوحمزة|Bouhamza", "مسيسنة|M'cisna", "صدوق|Seddouk", "بني مليكش|Beni-Mallikeche", "بو جليل|Boudjellil", "تازمالت|Tazmalt", "أكفادو|Akfadou", "شميني|Chemini", "سوق اوفلا|Souk Oufella", "طيبان|Tibane", "أوزلاقن|Ouzellaguen"]],
  ["07", "بسكرة", "Biskra", "Biskra", 800, "3-6", ["الفيض|El Feidh", "خنقة سيدي ناجي|Khangat Sidi Nadji", "زريبة الوادي|Zeribet El Oued", "المزيرعة|Meziraa", "ليشانة|Lichana", "بوشقرون|Bouchagroun", "برج بن عزوز|Bordj Ben Azzouz", "طولقة|Tolga", "مخادمة|Mekhadma", "مليلي|M’Lili", "أورلال|Ourlal", "أوماش|Oumache", "ليوة|Lioua", "بسكرة|Biskra", "الحاجب|El Hadjeb", "فوغالة|Foughala", "الغروس|El Ghrous", "عين الناقة|Ain Naga", "شتمة|Chetma", "الحوش|El Haouch", "سيدي عقبة|Sidi Okba", "مشونش|M’Chouneche"]],
  ["08", "بشار", "Bechar", "Bechar", 1100, "5-8", ["بشار|Bechar", "بوكايس|Boukais", "لحمر|Lahmar", "موغل|Mogheul", "المريجة|Meridja", "القنادسة|Kenadsa", "تاغيت|Taghit", "العبادلة|Abadla", "عرق فراج|Erg-Ferradj", "مشرع هواري بومدين|Machraa-Houari-Boumediene", "بني ونيف|Beni-Ounif", "تبلبالة|Tabelbala"]],
  ["09", "البليدة", "Blida", "Blida", 500, "1-3", ["بني مراد|Beni Mered", "أولاد يعيش|Ouled Yaich", "الشريعة|Chrea", "اولاد سلامة|Ouled Slama", "حمام ملوان|Hammam Elouane", "بوقرة|Bougara", "موزاية|Mouzaia", "الشفة|Chiffa", "عين الرمانة|Ain Romana", "صوحان|Souhane", "الأربعاء|Larbaa", "الصومعة|Soumaa", "قرواو|Guerrouaou", "بوفاريك|Boufarik", "مفتاح|Meftah", "جبابرة|Djebabra", "وادي جر|Oued  Djer", "العفرون|El-Affroun", "وادي العلايق|Oued El Alleug", "بن خليل|Benkhelil", "بني تامو|Beni-Tamou", "الشبلي|Chebli", "بوعينان|Bouinan", "بوعرفة|Bouarfa", "البليدة|Blida"]],
  ["10", "البويرة", "Bouira", "Bouira", 600, "2-4", ["عين العلوي|Ain Laloui", "عين الحجر|Ain El Hadjar", "عين بسام|Ain-Bessem", "الحجرة الزرقاء|Hadjera Zerga", "مزدور|Mezdour", "تاقديت|Taguedite", "برج أوخريص|Bordj Okhriss", "ريدان|Ridane", "المعمورة|Maamora", "الحاكمية|El-Hakimia", "ديرة|Dirah", "الدشمية|Dechmia", "سور الغزلان|Sour El Ghozlane", "أهل القصر|Ahl El Ksar", "بشلول|Bechloul", "العجيبة|El Adjiba", "الأسنام|El Asnam", "أولاد راشد|Ouled Rached", "آث  منصور|Ath Mansour", "سحاريج|Saharidj", "أمشدالة|M Chedallah", "حنيف|Hanif", "شرفة|Chorfa", "أغبالو|Aghbalou", "روراوة|Raouraoua", "الخبوزية|El Khabouzia", "بئر غبالو|Bir Ghbalou", "البويرة|Bouira", "عين الترك|Ain Turk", "أيت لعزيز|Ait Laaziz", "المقراني|El-Mokrani", "سوق الخميس|Souk El Khemis", "أعمر|Aomar", "جباحية|Djebahia", "قادرية|Kadiria", "الهاشمية|El Hachimia", "وادي البردي|Oued El Berdi", "حيزر|Haizer", "تاغزوت|Taghzout", "بودربالة|Bouderbala", "بوكرم|Boukram", "قرومة|Guerrouma", "الأخضرية|Lakhdaria", "معلة|Maala", "زبربر|Z'barbar (El Isseri )"]],
  ["11", "تمنراست", "Tamanrasset", "Tamanrasset", 1300, "5-8", ["تاظروك|Tazrouk", "أدلس|Idles", "ابلسة|Abelsa", "تمنراست|Tamanrasset", "عين امقل|Ain Amguel"]],
  ["12", "تبسة", "Tebessa", "Tebessa", 750, "3-5", ["الحويجبات|Lahouidjbet", "الماء الابيض|El Ma Labiod", "العوينات|El Aouinet", "بوخضرة|Boukhadra", "بئر مقدم|Bir Mokkadem", "قريقر|Gourrigueur", "الحمامات|Hammamet", "بئر الذهب|Bir Dheheb", "مرسط|Morsott", "صفصاف الوسرى|Safsaf El Ouesra", "أم علي|Oum Ali", "بكارية|Bekkaria", "بولحاف الدير|Boulhaf Dyr", "الكويف|El Kouif", "الونزة|Ouenza", "المريج|El Meridj", "عين الزرقاء|Ain Zerga", "سطح قنطيس|Stah Guentis", "العقلة|El Ogla", "المزرعة|El Mezeraa", "بجن|Bedjene", "ثليجان|Thlidjene", "الشريعة|Cheria", "تبسة|Tebessa"]],
  ["13", "تلمسان", "Tlemcen", "Tlemcen", 750, "3-5", ["باب العسة|Bab El Assa", "سوق الثلاثاء|Souk Thlata", "السواني|Souani", "تيرني بني هديل|Tirni Beni Hediel", "منصورة|Mansourah", "بني مستر|Beni Mester", "عين غرابة|Ain Ghoraba", "شتوان|Chetouane", "عمير|Amieur", "عين فزة|Ain Fezza", "هنين|Honaine", "بني خلاد|Beni Khellad", "ندرومة|Nedroma", "جبالة|Djebala", "مسيردة الفواقة|Msirda Fouaga", "مرسى بن مهيدي|Marsa Ben M’Hidi", "سيدي مجاهد|Sidi Medjahed", "بني بوسعيد|Beni Boussaid", "سبدو|Sebdou", "بوحلو|Bouhlou", "صبرة|Sabra", "مغنية|Maghnia", "حمام بوغرارة|Hammam Boughrara", "زناتة|Zenata", "أولاد رياح|Ouled Riyah", "الحناية|Hennaya", "سيدي العبدلي|Sidi Abdelli", "بن سكران|Bensekrane", "فلاوسن|Fellaoucene", "عين الكبيرة|Ain Kebira", "عين فتاح|Ain Fetah", "تلمسان|Tlemcen", "عين النحالة|Ain Nehala", "عين تالوت|Ain Tallout", "عين يوسف|Ain Youcef", "بني وارسوس|Beni Ouarsous", "الفحول|El Fehoul", "الرمشي|Remchi", "سبعة شيوخ|Sebaa Chioukh", "دار يغمراسن|Dar Yaghmouracene", "الغزوات|Ghazaouet", "السواحلية|Souahlia", "تيانت|Tianet", "بني صميل|Beni Semiel", "وادي الخضر|Oued Lakhdar", "أولاد ميمون|Ouled Mimoun", "بني بهدل|Beni Bahdel", "بني سنوس|Beni Snous", "العزايل|Azails"]],
  ["14", "تيارت", "Tiaret", "Tiaret", 750, "3-5", ["مهدية|Mahdia", "عين دزاريت|Ain Dzarit", "السبعين|Sebaine", "الناظورة|Nadorah", "الفايجة|Faidja", "سي عبد الغني|Sidi Abdelghani", "السوقر|Sougueur", "توسنينة|Tousnina", "مغيلة|Meghila", "السبت|Sebt", "سيدي حسني|Sidi Hosni", "عين الحديد|Ain El Hadid", "فرندة|Frenda", "تخمرت|Takhemaret", "عين كرمس|Ain Kermes", "جبيلات الرصفاء|Djebilet Rosfa", "مادنة|Madna", "مدريسة|Medrissa", "سيدي عبد الرحمن|Sidi Abderrahmane", "قرطوفة|Guertoufa", "الرحوية|Rahouia", "وادي ليلي|Oued Lili", "سيدي علي ملال|Sidi Ali Mellal", "تيدة|Tidda", "جيلالي بن عمار|Djileli Ben Amar", "مشرع الصفا|Mechraa Sfa", "تاقدمت|Tagdemt", "تيارت|Tiaret", "مدروسة|Medroussa", "ملاكو|Mellakou", "سيدي بختي|Sidi Bakhti", "عين الذهب|Ain Deheb", "شحيمة|Chehaima", "النعيمة|Naima", "عين بوشقيف|Ain Bouchekif", "دحموني|Dahmouni"]],
  ["15", "تيزي وزو", "Tizi Ouzou", "Tizi Ouzou", 600, "2-4", ["ميزرانـــة|Mizrana", "إفليـــسن|Iflissen", "تيقـزيرت|Tigzirt", "إيجــار|Idjeur", "بني زيكــي|Beni-Zikki", "إيلولة أومـــالو|Illoula Oumalou", "بوزقــن|Bouzeguene", "بني دوالة|Beni-Douala", "بني عيسي|Beni-Aissi", "أيت محمود|Ait-Mahmoud", "بنــــي زمنزار|Beni Zmenzer", "أقني قغران|Agouni-Gueghrane", "أيت بــوادو|Ait Bouaddou", "واضية|Ouadhias", "تيزي نثلاثة|Tizi N'tleta", "أغريب|Aghribs", "أيت شافع|Ait-Chafaa", "أقرو|Akerrou", "أزفون|Azeffoun", "أسي يوسف|Assi-Youcef", "بوغني|Boghni", "بونوح|Bounouh", "مشطراس|Mechtras", "ذراع بن خدة|Draa-Ben-Khedda", "سيدي نعمان|Sidi Namane", "تادمايت|Tadmait", "تيرمتين|Tirmitine", "أيت بومهدي|Ait Boumahdi", "أيت تودرت|Ait-Toudert", "واسيف|Ouacif", "أيت خليلي|Ait Khellili", "مقــلع|Mekla", "صوامـــع|Souama", "بني يني|Beni-Yenni", "إبودرارن|Iboudrarene", "يطــافن|Yatafene", "تيزي وزو|Tizi-Ouzou", "أبي يوسف|Abi-Youcef", "عين الحمام|Ain-El-Hammam", "أيت يحيى|Ait-Yahia", "اقبيل|Akbil", "بوجيمة|Boudjima", "ماكودة|Makouda", "عين الزاوية|Ain-Zaouia", "أيت يحي موسى|Ait Yahia Moussa", "ذراع الميزان|Draa-El-Mizan", "فريقات|Frikat", "مكيرة|M'kira", "تيزي غنيف|Tizi-Gheniff", "إيلـيــلتـن|Illilten", "إمســوحال|Imsouhal", "إفــرحــونان|Iferhounene", "عزازقة|Azazga", "فريحة|Freha", "إيفيغاء|Ifigha", "إعــكورن|Yakourene", "زكري|Zekri", "أيت عقـواشة|Ait Aggouacha", "إيرجـــن|Irdjen", "الأربعــاء ناث إيراثن|Larbaa Nath Irathen", "أيت  أومالو|Ait-Oumalou", "تيزي راشد|Tizi-Rached", "أيت عيسى ميمون|Ait-Aissa-Mimoun", "واقنون|Ouaguenoun", "تيمـيزار|Timizart", "معـــاتقة|Maatkas", "سوق الإثنين|Souk-El-Tenine"]],
  ["16", "الجزائر", "Alger", "Alger", 400, "1-2", ["حسين داي|Hussein Dey", "القبة|Kouba", "محمد بلوزداد|Mohamed Belouzdad", "المغارية|El Magharia", "الكاليتوس|Les Eucalyptus", "سيدي موسى|Sidi Moussa", "براقي|Baraki", "عين طاية|Ain Taya", "باب الزوار|Bab Ezzouar", "برج الكيفان|Bordj El Kiffan", "الدار البيضاء|Dar El Beida", "المحمدية|Mohammadia", "برج البحري|Bordj El Bahri", "المرسى|El Marsa", "بئر توتة|Bir Touta", "اولاد شبل|Ouled Chebel", "تسالة المرجة|Tessala El Merdja", "هراوة|Herraoua", "رغاية|Reghaia", "الرويبة|Rouiba", "المعالمة|Maalma", "الرحمانية|Rahmania", "سويدانية|Souidania", "سطاوالي|Staoueli", "زرالدة|Zeralda", "بابا حسن|Baba Hassen", "الدويرة|Douira", "الدرارية|Draria", "العاشور|El Achour", "الخرايسية|Khraissia", "عين بنيان|Ain Benian", "الشراقة|Cheraga", "دالي ابراهيم|Dely Ibrahim", "اولاد فايت|Ouled Fayet", "الحمامات|Hammamet", "الجزائر الوسطى|Alger Centre", "المدنية|El Madania", "المرادية|El Mouradia", "سيدي امحمد|Sidi M'hamed", "السحاولة|Sehaoula", "بئر مراد رايس|Bir Mourad Rais", "بئر خادم|Birkhadem", "جسر قسنطينة|Djasr Kasentina", "حيدرة|Hydra", "بولوغين بن زيري|Bologhine Ibnou Ziri", "القصبة|Casbah", "وادي قريش|Oued Koriche", "الرايس حميدو|Rais Hamidou", "باب الوادي|Bab El Oued", "ابن عكنون|Ben Aknoun", "بني مسوس|Beni Messous", "بوزريعة|Bouzareah", "الابيار|El Biar", "باش جراح|Bachedjerah", "بوروبة|Bourouba", "الحراش|El Harrach", "وادي السمار|Oued Smar"]],
  ["17", "الجلفة", "Djelfa", "Djelfa", 800, "3-6", ["حاسي العش|Hassi El Euch", "زعفران|Zaafrane", "عين معبد|Ain Maabed", "حاسي بحبح|Hassi Bahbah", "عين الإبل|Ain El Ibel", "تعظميت|Tadmit", "زكار|Zaccar", "مجبارة|Moudjbara", "القديد|El Gueddid", "الشارف|Charef", "بن يعقوب|Ben Yaagoub", "سيدي بايزيد|Sidi Baizid", "مليليحة|M’Liliha", "دار الشيوخ|Dar Chioukh", "دويس|Douis", "الادريسية|El Idrissia", "عين الشهداء|Ain Chouhada", "الجلفة|Djelfa"]],
  ["18", "جيجل", "Jijel", "Jijel", 700, "3-5", ["جيجل|Jijel", "العوانة|El Aouana", "سلمى بن زيادة|Selma Benziada", "أراقن سويسي|Erraguene Souissi", "زيامة منصورية|Ziama Mansouriah", "بوسيف أولاد عسكر|Boussif Ouled Askeur", "الشحنة|Chahna", "الامير عبد القادر|Emir Abdelkader", "وجانة|Oudjana", "الطاهير|Taher", "الشقفة|Chekfa", "القنار نشفي|El Kennar Nouchfi", "سيدي عبد العزيز|Sidi Abdelaziz", "برج الطهر|Bordj T'har", "الميلية|El Milia", "أولاد يحيى خدروش|Ouled Yahia Khadrouch", "أولاد رابح|Ouled Rabah", "سيدي معروف|Sidi Marouf", "غبالة|Ghebala", "السطارة|Settara", "بوراوي بلهادف|Bouraoui Belhadef", "العنصر|El Ancer", "خيري واد عجول|Khiri Oued Adjoul", "الجمعة بني حبيبي|Djemaa Beni Habibi", "جيملة|Djimla", "بودريعة بني  ياجيس|Boudria Beniyadjis", "قاوس|Kaous", "تاكسنة|Texenna"]],
  ["19", "سطيف", "Setif", "Setif", 600, "2-4", ["الرصفة|Rosfa", "بوطالب|Boutaleb", "الحامة|Hamma", "أولاد تبان|Ouled Tebben", "صالح باي|Salah Bey", "واد البارد|Oued El Bared", "تيزي نبشار|Tizi N'bechar", "عموشة|Amoucha", "مزلوق|Mezloug", "أوريسيا|El Ouricia", "عين عباسة|Ain Abessa", "عين أرنات|Ain Arnat", "قلال|Guellal", "قصر الابطال|Kasr El Abtal", "أولاد سي أحمد|Ouled Si Ahmed", "عين ولمان|Ain Oulmene", "أيت نوال مزادة|Ait Naoual Mezada", "ايت تيزي|Ait-Tizi", "بوعنداس|Bouandas", "بوسلام|Bousselam", "حمام السخنة|Hamam Soukhna", "الطاية|Taya", "التلة|Tella", "عين أزال|Ain Azel", "عين الحجر|Ain Lahdjar", "بيضاء برج|Beidha Bordj", "بئر حدادة|Bir Haddada", "قنزات|Guenzet", "حربيل|Harbil", "عين الروى|Ain-Roua", "بني وسين|Beni Oussine", "بوقاعة|Bougaa", "ذراع قبيلة|Draa-Kebila", "حمام قرقور|Hammam Guergour", "سطيف|Setif", "عين الكبيرة|Ain El Kebira", "الدهامشة|Dehamcha", "أولاد عدوان|Ouled Addouane", "عين السبت|Ain-Sebt", "بني عزيز|Beni-Aziz", "معاوية|Maaouia", "بلاعة|Bellaa", "بئر العرش|Bir-El-Arch", "الولجة|El-Ouldja", "تاشودة|Tachouda", "تالة إيفاسن|Tala-Ifacene", "ماوكلان|Maouaklane", "سرج الغول|Serdj-El-Ghoul", "بابور|Babor", "قجال|Guidjel", "أولاد صابر|Ouled Sabor", "بازر سكرة|Bazer-Sakra", "العلمة|El Eulma", "قلتة زرقاء|Guelta Zerka", "بني فودة|Beni Fouda", "جميلة|Djemila", "عين لقراج|Ain-Legradj", "بني شبانة|Beni Chebana", "بني ورتيلان|Beni Ourtilane", "بني موحلي|Beni-Mouhli"]],
  ["20", "سعيدة", "Saida", "Saida", 800, "3-5", ["سعيدة|Saida", "تيرسين|Tircine", "أولاد إبراهيم|Ouled Brahim", "عين السلطان|Ain Soltane", "المعمورة|Maamora", "الحساسنة|El Hassasna", "عين السخونة|Ain Sekhouna", "سيدي بوبكر|Sidi Boubekeur", "أولاد خالد|Ouled Khaled", "هونت|Hounet", "سيدي عمر|Sidi Amar", "يوب|Youb", "دوي ثابت|Doui Thabet", "سيدي احمد|Sidi Ahmed", "مولاي العربي|Moulay Larbi", "عين الحجر|Ain El Hadjar"]],
  ["21", "سكيكدة", "Skikda", "Skikda", 700, "3-5", ["عين بوزيان|Ain Bouziane", "بني ولبان|Beni Oulbane", "سيدي مزغيش|Sidi Mezghiche", "صالح بو الشعور|Salah Bouchaour", "زردازة|Zerdezas", "أولاد حبابة|Ouled Habbaba", "مجاز الدشيش|Emjez Edchich", "الحروش|El Arrouch", "الحدائق|El Hadaiek", "بوشطاطة|Bouchetata", "عين زويت|Ain Zouit", "بني بشير|Beni Bechir", "رمضان جمال|Ramdane Djamel", "بين الويدان|Bin El Ouiden", "تمالوس|Tamalous", "الكركرة|Kerkara", "عين قشرة|Ain Kechra", "الولجة بولبلوط|Ouldja Boulbalout", "أم الطوب|Oum Toub", "الغدير|El Ghedir", "السبت|Es Sebt", "عين شرشار|Ain Charchar", "عزابة|Azzaba", "جندل سعدي محمد|Djendel Saadi Mohamed", "الزيتونة|Zitouna", "قنواع|Kanoua", "أولاد عطية|Ouled Attia", "وادي الزهور|Oued Zhour", "خناق مايو|Khenag Maoune", "القل|Collo", "الشرايع|Cheraia", "بني زيد|Beni Zid", "المرسى|El Marsa", "بن عزوز|Ben Azzouz", "بكوش لخضر|Bekkouche Lakhdar", "فلفلة|Filfila", "حمادي كرومة|Hammadi Krouma", "سكيكدة|Skikda"]],
  ["22", "سيدي بلعباس", "Sidi Bel Abbes", "Sidi Bel Abbes", 750, "3-5", ["سيدي علي بن يوب|Sidi Ali Benyoub", "طابية|Tabia", "بوخنفيس|Boukhanefis", "مولاي سليسن|Moulay Slissen", "الحصيبة|El Hacaiba", "عين تندمين|Ain Tindamine", "تنيرة|Tenira", "وادي سفيون|Oued Sefioun", "حاسي دحو|Hassi Dahou", "بن عشيبة شلية|Benachiba Chelia", "وادي تاوريرة|Oued Taourira", "مرين|Merine", "تفسور|Tefessour", "تاودموت|Taoudmout", "سيدي يعقوب|Sidi Yacoub", "سيدي لحسن|Sidi Lahcene", "سيدي خالد|Sidi Khaled", "العمارنة|Amarnas", "سيدي ابراهيم|Sidi Brahim", "سيدي حمادوش|Sidi Hamadouche", "مكدرة|Makedra", "عين البرد|Ain El Berd", "حاسي زهانة|Hassi Zahana", "شيطوان البلايلة|Chetouane Belaila", "بن باديس|Ben Badis", "بضرابين المقراني|Bedrabine El Mokrani", "سفيزف|Sfisef", "مسيد|M'cid", "بوجبهة البرج|Boudjebaa El Bordj", "عين أدن|Ain- Adden", "سيدي شعيب|Sidi Chaib", "مرحوم|Marhoum", "بئر الحمام|Bir El Hammam", "رجم دموش|Redjem Demouche", "راس الماء|Ras El Ma", "وادي السبع|Oued Sebaa", "سيدي بلعباس|Sidi Bel-Abbes", "عين الثريد|Ain Thrid", "السهالة الثورة|Sehala Thaoura", "تسالة|Tessala", "بلعربي|Belarbi", "مصطفى بن ابراهيم|Mostefa  Ben Brahim", "تلموني|Tilmouni", "زروالة|Zerouala", "الضاية|Dhaya", "مزاورو|Mezaourou", "تغاليمت|Teghalimet", "تلاغ|Telagh", "عين قادة|Ain Kada", "لمطار|Lamtar", "سيدي علي بوسيدي|Sidi Ali Boussidi", "سيدي دحو الزاير|Sidi Dahou Zairs"]],
  ["23", "عنابة", "Annaba", "Annaba", 650, "2-4", ["عنابة|Annaba", "سرايدي|Seraidi", "برحال|Berrahal", "واد العنب|Oued El Aneb", "التريعات|Treat", "الحجار|El Hadjar", "سيدي عمار|Sidi Amar", "البوني|El Bouni", "عين الباردة|Ain El Berda", "الشرفة|Cheurfa", "العلمة|El Eulma", "شطايبي|Chetaibi"]],
  ["24", "قالمة", "Guelma", "Guelma", 700, "3-5", ["نشماية|Nechmaya", "بومهرة أحمد|Boumahra Ahmed", "جبالة الخميسي|Djeballah Khemissi", "بلخير|Belkheir", "بني مزلين|Beni Mezline", "قلعة بوصبع|Guelaat Bou Sbaa", "بوحمدان|Bou Hamdane", "حمام دباغ|Hammam Debagh", "الركنية|Roknia", "الدهوارة|Dahouara", "حمام النبايل|Hammam N'bail", "وادي الشحم|Oued Cheham", "قالمة|Guelma", "بن جراح|Bendjarah", "عين بن بيضاء|Ain Ben Beida", "بوشقوف|Bouchegouf", "مجاز الصفاء|Medjez Sfa", "وادي فراغة|Oued Ferragha", "بوعاتي محمود|Bouati Mahmoud", "الفجوج|El Fedjoudj", "هيليوبوليس|Heliopolis", "مجاز عمار|Medjez Amar", "هواري بومدين|Houari Boumedienne", "رأس العقبة|Ras El Agba", "سلاوة عنونة|Sellaoua Announa", "برج صباط|Bordj Sabath", "وادي الزناتي|Oued Zenati", "عين رقادة|Ain Regada", "عين العربي|Ain Larbi", "عين مخلوف|Ain Makhlouf", "تاملوكة|Tamlouka", "عين صندل|Ain Sandel", "بوحشانة|Bou Hachana", "لخزارة|Khezaras"]],
  ["25", "قسنطينة", "Constantine", "Constantine", 600, "2-4", ["ديدوش مراد|Didouche Mourad", "حامة بوزيان|Hamma Bouziane", "بني حميدان|Beni Hamidane", "زيغود يوسف|Zighoud Youcef", "عين السمارة|Ain Smara", "الخروب|El Khroub", "أولاد رحمون|Ouled Rahmoun", "عين عبيد|Ain Abid", "أبن باديس الهرية|Ben Badis", "ابن زياد|Ibn Ziad", "بوجريو مسعود|Messaoud Boudjeriou", "قسنطينة|Constantine"]],
  ["26", "المدية", "Medea", "Medea", 600, "2-4", ["السواقي|Souagui", "جواب|Djouab", "سيدي زهار|Sidi Zahar", "سيدي زيان|Sidi Ziane", "العزيزية|Al Azizia", "مغراوة|Meghraoua", "ميهوب|Mihoub", "حناشة|Hannacha", "عوامري|Ouamri", "وادي حربيل|Oued Harbil", "بني سليمان|Beni Slimane", "بوسكن|Bouskene", "سيدي الربيع|Sidi Errabie", "بوعيشون|Bouaichoune", "أولاد بوعشرة|Ouled Bouachra", "سي المحجوب|Si Mahdjoub", "البرواقية|Berrouaghia", "أولاد دايد|Ouled Deide", "الربعية|Rebaia", "مجبر|Medjebar", "ثلاث دوائر|Eddouair", "الزبيرية|Zoubiria", "سغوان|Seghouane", "العيساوية|Aissaouia", "الحوضان|El Hamdania", "مزغنة|Medea", "تابلاط|Tablat", "ذراع السمار|Draa Essamar", "المدية|Ouzera", "تمسقيدة|Tamezguida", "بن شكاو|Benchicao", "الحمدانية|El Omaria", "وزرة|Baata", "تيزي مهدي|Tizi Mahdi", "بعطة|Sedraia", "العمارية|Mezghenna", "أولاد إبراهيم|Ouled Brahim", "بئر بن عابد|Bir Ben Abed", "القلب الكبير|El Guelb El Kebir", "سدراية|Sidi Naamane", "بوشراحيل|Bouchrahil", "خمس جوامع|Khamsa Djoumaa", "سيدي نعمان|Deux Bassins"]],
  ["27", "مستغانم", "Mostaganem", "Mostaganem", 700, "3-5", ["فرناقة|Fornaka", "الحسيان (بني ياحي|Hassiane", "عين نويسي|Ain-Nouissy", "وادي الخير|Oued El Kheir", "عين تادلس|Ain-Tedles", "سيدي بلعطار|Sidi Belaattar", "سور|Sour", "حاسي ماماش|Hassi Mameche", "مزغران|Mazagran", "ستيدية|Stidia", "عين بودينار|Ain-Boudinar", "خير الدين|Kheir-Eddine", "صيادة|Sayada", "سيدي علي|Sidi Ali", "تزقايت|Tazgait", "أولاد مع الله|Ouled-Maalah", "بن عبد المالك رمضان|Benabdelmalek Ramdane", "حجاج|Hadjadj", "سيدي لخضر|Sidi-Lakhdar", "مستغانم|Mostaganem", "عشعاشة|Achaacha", "خضرة|Khadra", "نكمارية|Nekmaria", "أولاد بوغالم|Ouled Boughalem", "بوقيراط|Bouguirat", "صفصاف|Safsaf", "سيرات|Sirat", "السوافلية|Souaflia", "عين سيدي الشريف|Ain-Sidi Cherif", "ماسرة|Mesra", "الطواهرية|Touahria", "منصورة|Mansourah"]],
  ["28", "المسيلة", "M'Sila", "M'Sila", 700, "3-5", ["المسيلة|M’Sila", "شلال|Chellal", "أولاد ماضي|Ouled Madhi", "خطوطي سد الجير|Khetouti Sed El Djir", "المعاريف|Maarif", "مقرة|Magra", "برهوم|Berhoum", "عين الخضراء|Ain Khadra", "بلعايبة|Belaiba", "دهاهنة|Dehahna", "سيدي عيسى|Sidi Aissa", "بوطي السايح|Bouti Sayah", "بني يلمان|Beni Ilmane", "عين الحجل|Ain El Hadjel", "سيدي هجرس|Sidi Hadjeres", "حمام الضلعة|Hammam Dhalaa", "ونوغة|Ouanougha", "أولاد منصور|Ouled Mansour", "تارمونت|Tarmount", "أولاد دراج|Ouled Derradj", "السوامع|Souamaa", "أولاد عدي لقبالة|Ouled Addi Guebala", "المعاضيد|Maadid", "امطارفة|M’Tarfa"]],
  ["29", "معسكر", "Mascara", "Mascara", 750, "3-5", ["وادي الأبطال|Oued El Abtal", "سيدي عبد الجبار|Sidi Abdeldjebar", "عين فراح|Ain Ferah", "سيدي عبد المومن|Sidi Abdelmoumene", "سجرارة|Sedjerara", "مقطع الدوز|Mocta-Douz", "فراقيق|Ferraguig", "الغمري|El Ghomri", "المحمدية|Mohammadia", "تيغنيف|Tighennif", "سيدي قادة|Sidi Kada", "السهايلية|Sehailia", "زهانة|Zahana", "القعدة|El Gaada", "رأس عين عميروش|Ras El Ain Amirouche", "عقاز|Oggaz", "العلايمية|Alaimia", "سيق|Sig", "الشرفاء|Chorfa", "بوهني|Bou Henni", "المأمونية|El Mamounia", "القطنة|El Gueitena", "بوحنيفية|Bouhanifia", "حسين|Hacine", "عين فارس|Ain Fares", "غروس|Gharrous", "بنيان|Benian", "عوف|Aouf", "قرجوم|Guerdjoum", "وادي التاغية|Oued Taria", "عين أفرص|Ain Frass", "عين فكان|Ain Fekan", "خلوية|Khalouia", "المنور|El Menaouer", "البرج|El Bordj", "سيدي بوسعيد|Sidi Boussaid", "المطمور|Matemore", "ماقضة|Makhda", "غريس|Ghriss", "ماوسة|Maoussa", "معسكر|Mascara", "القرط|El Keurt", "فروحة|Froha", "تيزي|Tizi", "الحشم|El Hachem", "نسمط|Nesmot", "زلامطة|Zelamta"]],
  ["30", "ورقلة", "Ouargla", "Ouargla", 950, "4-7", ["ورقلة|Ouargla", "الرويسات|Rouissat", "حاسي مسعود|Hassi Messaoud", "عين البيضاء|Ain Beida", "حاسي بن عبد الله|Hassi Ben Abdellah", "سيدي خويلد|Sidi Khouiled", "البرمة|El Borma", "انقوسة|N'goussa"]],
  ["31", "وهران", "Oran", "Oran", 600, "2-4", ["سيدي الشحمي|Sidi Chami", "الكرمة|El Kerma", "السانية|Es Senia", "حاسي مفسوخ|Hassi Mefsoukh", "قديل|Gdyel", "بن فريحة|Ben Freha", "بئر الجير|Bir El Djir", "حاسي بن عقبة|Hassi Ben Okba", "حاسي بونيف|Hassi Bounif", "أرزيو|Arzew", "سيدي بن يبقى|Sidi Ben Yebka", "عين البية|Ain Biya", "بطيوة|Bethioua", "مرسى الحجاج|Marsat El Hadjadj", "عين الترك|Ain Turk", "وهران|Oran", "العنصر|El Ancor", "المرسى الكبير|Mers El Kebir", "بوسفر|Bousfer", "بوفاتيس|Boufatis", "البراية|El Braya", "وادي تليلات|Oued Tlelat", "طفراوي|Tafraoui", "عين الكرمة|Ain Kerma", "بوتليليس|Boutlelis", "مسرغين|Messerghin"]],
  ["32", "البيض", "El Bayadh", "El Bayadh", 950, "4-6", ["البيض|El Bayadh", "رقاصة|Rogassa", "الشقيق|Cheguig", "الكاف الأحمر|Kef El Ahmar", "بريزينة|Brezina", "غسول|Ghassoul", "كراكدة|Krakda", "بوقطب|Bougtob", "الخيثر|El Kheither", "توسمولين|Tousmouline", "بوعلام|Boualem", "سيدي سليمان|Sidi Slimane", "سيدي طيفور|Sidi Tifour", "ستيتن|Stitten", "سيدي عامر|Sidi Amar"]],
  ["33", "إليزي", "Illizi", "Illizi", 1400, "6-9", ["برج عمر إدريس|Bordj Omar Driss", "دبداب|Debdeb", "إن أمناس|In Amenas", "إيليزي|Illizi"]],
  ["34", "برج بوعريريج", "Bordj Bou Arreridj", "Bordj Bou Arreridj", 600, "2-4", ["الحمادية|Elhammadia", "العش|El Euch", "القصور|Ksour", "الرابطة|Rabta", "أولاد سيدي ابراهيم|Ouled Sidi-Brahim", "عين تاغروت|Ain Taghrout", "تيكستار|Tixter", "بليمور|Belimour", "العناصر|El Annasseur", "غيلاسة|Ghailasa", "تقلعيت|Taglait", "برج الغدير|Bordj Ghedir", "سيدي أمبارك|Sidi-Embarek", "خليل|Khelil", "بئر قاصد علي|Bir Kasdali", "تفرق|Tefreg", "الماين|El Main", "جعافرة|Djaafra", "القلة|Colla", "ثنية النصر|Teniet En Nasr", "الياشير|El Achir", "حسناوة|Hasnaoua", "مجانة|Medjana", "المهير|El M'hir", "المنصورة|Mansoura", "حرازة|Haraza", "بن داود|Ben Daoud", "عين تسرة|Ain Tesra", "أولاد أبراهم|Ouled Brahem", "رأس الوادي|Ras El Oued", "برج زمورة|Bordj Zemmoura", "أولاد دحمان|Ouled Dahmane", "تسامرت|Tassamert", "برج بوعريرج|B. B. Arreridj"]],
  ["35", "بومرداس", "Boumerdes", "Boumerdes", 500, "1-3", ["الخروبة|El Kharrouba", "بوزقزة قدارة|Bouzegza Keddara", "أولاد هداج|Ouled Hedadj", "بودواو|Boudouaou", "بودواو البحري|Boudouaou El Bahri", "دلس|Dellys", "بن شود|Ben Choud", "أعفير|Afir", "الثنية|Thenia", "بني عمران|Beni Amrane", "عمال|Ammal", "سوق الحد|Souk El Had", "خميس الخشنة|Khemis El Khechna", "الاربعطاش|Larbatache", "أولاد موسى|Ouled Moussa", "حمادي|Hammedi", "تيمزريت|Timezrit", "زموري|Zemmouri", "لقاطة|Leghata", "جنات|Djinet", "برج منايل|Bordj Menaiel", "يسر|Isser", "شعبة العامر|Chabet El Ameur", "سي مصطفى|Si Mustapha", "أولاد عيسى|Ouled Aissa", "الناصرية|Naciria", "سيدي داود|Sidi Daoud", "بغلية|Baghlia", "تاورقة|Taourga", "تيجلابين|Tidjelabine", "بومرداس|Boumerdes", "قورصو|Corso"]],
  ["36", "الطارف", "El Tarf", "El Tarf", 700, "3-5", ["عين العسل|Ain El Assel", "بوقوس|Bougous", "الطارف|El Tarf", "الزيتونة|Zitouna", "البسباس|Besbes", "زريزر|Zerizer", "عصفور|Asfour", "عين الكرمة|Ain Kerma", "بوحجار|Bouhadjar", "حمام بني صالح|Hammam Beni Salah", "وادي الزيتون|Oued Zitoun", "بن مهيدي|Ben M Hidi", "بريحان|Berrihane", "الشط|Echatt", "شبيطة مختار|Chebaita Mokhtar", "شحاني|Chihani", "الذرعـان|Drean", "العيون|El Aioun", "القالة|El Kala", "السوارخ|Souarekh", "رمل السوق|Raml Souk", "بوثلجة|Bouteldja", "الشافية|Chefia", "بحيرة الطيور|Lac Des Oiseaux"]],
  ["37", "تندوف", "Tindouf", "Tindouf", 1500, "6-9", ["تندوف|Tindouf", "أم العسل|Oum El Assel"]],
  ["38", "تسمسيلت", "Tissemsilt", "Tissemsilt", 750, "3-5", ["خميستي|Khemisti", "العيون|Layoune", "ثنية الاحد|Theniet El Had", "سيدي بوتوشنت|Sidi Boutouchent", "أولاد بسام|Ouled Bessam", "تيسمسيلت|Tissemsilt", "سيدي العنتري|Sidi Lantri", "لرجام|Lardjem", "الملعب|Melaab", "تملاحت|Tamellahet", "بني شعيب|Beni Chaib", "بني لحسن|Beni Lahcene", "برج بونعامة|Bordj Bounaama", "سيدي عابد|Sidi Abed", "عماري|Ammari", "المعاصم|Maacem", "سيدي سليمان|Sidi Slimane", "بوقائد|Boucaid", "الأزهرية|Lazharia", "الأربعاء|Larbaa", "اليوسفية|Youssoufia", "برج الأمير عبد القادر|Bordj El Emir Abdelkader"]],
  ["39", "الوادي", "El Oued", "El Oued", 950, "4-7", ["دوار الماء|Douar El Maa", "بن  قشة|Ben Guecha", "الطالب العربي|Taleb Larbi", "العقلة|El Ogla", "المقرن|Magrane", "سيدي عون|Sidi Aoun", "اميه وانسة|Mih Ouansa", "وادي العلندة|Oued El Alenda", "كوينين|Kouinine", "الوادي|El-Oued", "البياضة|Bayadha", "النخلة|Nakhla", "الرباح|Robbah", "قمار|Guemar", "ورماس|Ourmes", "تغزوت|Taghzout", "الحمراية|Hamraia", "الرقيبة|Reguiba", "الدبيلة|Debila", "حساني عبد الكريم|Hassani Abdelkrim", "حاسي خليفة|Hassi Khalifa", "الطريفاوي|Trifaoui"]],
  ["40", "خنشلة", "Khenchela", "Khenchela", 800, "3-6", ["خيران|Khirane", "جلال|Djellal", "الولجة|El Oueldja", "ششار|Chechar", "بابار|Babar", "المحمل|El Mahmal", "أولاد رشاش|Ouled Rechache", "يابوس|Yabous", "شلية|Chelia", "بوحمامة|Bouhmama", "مصارة|M'sara", "خنشلة|Khenchela", "قايس|Kais", "الرميلة|Remila", "تاوزيانت|Taouzianat", "بغاي|Baghai", "الحامة|El Hamma", "انسيغة|Ensigha", "طامزة|Tamza", "عين الطويلة|Ain Touila", "متوسة|M'toussa"]],
  ["41", "سوق أهراس", "Souk Ahras", "Souk Ahras", 750, "3-5", ["سوق أهراس|Souk Ahras", "عين سلطان|Ain Soltane", "سدراتة|Sedrata", "خميسة|Khemissa", "الحنانشة|Hanencha", "المشروحة|Machroha", "عين الزانة|Ain Zana", "أولاد إدريس|Ouled Driss", "ترقالت|Terraguelt", "أم العظايم|Oum El Adhaim", "وادي الكبريت|Oued Kebrit", "تيفاش|Tiffech", "الراقوبة|Ragouba", "مداوروش|M'daourouche", "الدريعة|Drea", "تاورة|Taoura", "الزعرورية|Zaarouria", "الحدادة|Haddada", "الخضارة|Khedara", "أولاد مومن|Ouled Moumen", "المراهنة|Merahna", "ويلان|Ouillen", "سيدي فرج|Sidi Fredj", "بئر بوحوش|Bir Bouhouche", "سافل الويدان|Safel El Ouiden", "الزوابي|Zouabi"]],
  ["42", "تيبازة", "Tipaza", "Tipaza", 450, "1-3", ["حجوط|Hadjout", "مراد|Merad", "مناصر|Menaceur", "الناظور|Nador", "سيدي عامر|Sidi-Amar", "أغبال|Aghbal", "قوراية|Gouraya", "مسلمون|Messelmoun", "شرشال|Cherchell", "حجرة النص|Hadjret Ennous", "سيدي غيلاس|Sidi Ghiles", "سيدي سميان|Sidi Semiane", "الداموس|Damous", "الأرهاط|Larhat", "بني ميلك|Beni Mileuk", "فوكة|Fouka", "دواودة|Douaouda", "عين تاقورايت|Ain Tagourait", "بوهارون|Bou Haroun", "بواسماعيل|Bou Ismail", "خميستي|Khemisti", "أحمر العين|Ahmer El Ain", "بورقيقة|Bourkika", "سيدي راشد|Sidi Rached", "الحطاطبة|Attatba", "الشعيبة|Chaiba", "القليعة|Kolea", "تيبازة|Tipaza"]],
  ["43", "ميلة", "Mila", "Mila", 650, "2-4", ["مشيرة|El Mechira", "التلاغمة|Teleghma", "وادي سقان|Oued Seguen", "العياضي برباس|El Ayadi Barbes", " عين البيضاء أحريش|Ain Beida Harriche", "تسالة لمطاعي|Tassala Lematai", "ترعي باينان|Terrai Bainen", "اعميرة اراس|Amira Arres", "تسدان حدادة|Tassadane Haddada", "مينار زارزة|Minar Zarza", "سيدي مروان|Sidi Merouane", "الشيقارة|Chigara", "حمالة|Hamala", "القرارم قوقة|Grarem Gouga", "تيبرقنت|Tiberguent", "الرواشد|Rouached", "دراحي بوصلاح|Derrahi Bousselah", "بوحاتم|Bouhatem", "زغاية|Zeghaia", "وادي النجاء|Oued Endja", "أحمد راشدي|Ahmed Rachedi", "تاجنانت|Tadjenanet", "أولاد اخلوف|Ouled Khalouf", "بن يحي عبد الرحمن|Benyahia Abderrahmane", "عين الملوك|Ain Mellouk", "وادي العثمانية|Oued Athmenia", "شلغوم العيد|Chelghoum Laid", "عين التين|Ain Tine", "سيدي خليفة|Sidi Khelifa", "ميلة|Mila", "يحي بني قشة|Yahia Beniguecha", "فرجيوة|Ferdjioua"]],
  ["44", "عين الدفلى", "Ain Defla", "Ain Defla", 650, "2-4", ["خميس مليانة|Khemis-Miliana", "سيدي الأخضر|Sidi-Lakhdar", "عين البنيان|Ain-Benian", "عين التركي|Ain-Torki", "حمام ريغة|Hammam-Righa", "بوراشد|Bourached", "جليدة|Djelida", "جمعة أولاد الشيخ|Djemaa Ouled Cheikh", "الحسينية|Hoceinia", "بومدفع|Boumedfaa", "عريب|Arib", "العامرة|El-Amra", "المخاطرية|Mekhatria", "العطاف|El-Attaf", "تبركانين|Tiberkanine", "عين بويحيى|Ain-Bouyahia", "العبادية|El-Abadia", "تاشتة زقاغة|Tacheta Zegagha", "بربوش|Birbouche", "جندل|Djendel", "وادي الشرفاء|Oued Chorfa", "بن علال|Ben Allal", "مليانة|Miliana", "عين الاشياخ|Ain-Lechiakh", "واد الجمعة|Oued Djemaa", "عين السلطان|Ain-Soltane", "الماين|El-Maine", "الروينة|Rouina", "زدين|Zeddine", "بئر ولد خليفة|Bir-Ould-Khelifa", "برج الأمير خالد|Bordj-Emir-Khaled", "طارق بن زياد|Tarik-Ibn-Ziad", "بطحية|Bathia", "بلعاص|Belaas", "الحسانية|Hassania", "عين الدفلى|Ain-Defla"]],
  ["45", "النعامة", "Naama", "Naama", 1000, "4-7", ["تيوت|Tiout", "عين الصفراء|Ain Sefra", "مغرار|Moghrar", "جنين بورزق|Djenienne Bourezg", "عسلة|Asla", "القصدير|Kasdir", "مكمن بن عمار|Makmen Ben Amar", "المشرية|Mecheria", "البيوض|El Biodh", "عين بن خليل|Ain Ben Khelil", "النعامة|Naama", "سفيسيفة|Sfissifa"]],
  ["46", "عين تموشنت", "Ain Temouchent", "Ain Temouchent", 750, "3-5", ["سيدي بومدين|Sidi Boumediene", "تامزورة|Tamzoura", "وادي الصباح|Oued Sebbah", "عين الأربعاء|Ain El Arbaa", "شعبة اللحم|Chaabat El Ham", "المالح|El Maleh", "أولاد الكيحل|Ouled Kihal", "تارقة|Terga", "شنتوف|Chentouf", "الحساسنة|Hassasna", "وادي برقش|Oued Berkeche", "حمام بوحجر|Hammam Bou Hadjar", "العامرية|El Amria", "حاسي الغلة|Hassi El Ghella", "أولاد بوجمعة|Ouled Boudjemaa", "المساعيد|El Messaid", "بوزجار|Bouzedjar", "أغلال|Aghlal", "عين الكيحل|Ain Kihal", "عين الطلبة|Ain Tolba", "عقب الليل|Aoubellil", "بني صاف|Beni Saf", "سيدي صافي|Sidi Safi", "الأمير عبد القادر|Emir Abdelkader", "ولهاصة الغرابة|Oulhaca El Gheraba", "سيدي ورياش|Sidi Ouriache", "سيدي بن عدة|Sidi Ben Adda", "عين تموشنت|Ain Temouchent"]],
  ["47", "غرداية", "Ghardaia", "Ghardaia", 950, "4-7", ["ضاية بن ضحوة|Dhayet Bendhahoua", "المنصورة|Mansoura", "العطف|El Atteuf", "بونورة|Bounoura", "زلفانة|Zelfana", "القرارة|El Guerrara", "سبسب|Sebseb", "متليلي|Metlili", "بريان|Berriane", "غرداية|Ghardaia"]],
  ["48", "غليزان", "Relizane", "Relizane", 700, "3-5", ["القطار|El-Guettar", "مازونة|Mazouna", "أولاد يعيش|Ouled Aiche", "عمي موسى|Ammi Moussa", "بني درقن|Beni Dergoun", "دار بن عبد الله|Dar Ben Abdelah", "زمورة|Zemmoura", "جديوية|Djidiouia", "حمري|Hamri", "أولاد سيدي الميهوب|Ouled Sidi Mihoub", "بلعسل بوزقزة|Belaassel Bouzagza", "المطمر|El-Matmar", "سيدي  خطاب|Sidi Khettab", "سيدي امحمد بن عودة|Sidi M'hamed Benaouda", "عين طارق|Ain-Tarek", "حد الشكالة|Had Echkalla", "الولجة|El Ouldja", "عين الرحمة|Ain Rahma", "القلعة|Kalaa", "سيدي سعادة|Sidi Saada", "يلل|Yellel", "سوق الحد|Souk El Had", "منداس|Mendes", "وادي السلام|Oued Essalem", "سيدي لزرق|Sidi Lazreg", "واريزان|Ouarizane", "مرجة سيدي عابد|Merdja Sidi Abed", "وادي رهيو|Oued-Rhiou", "لحلاف|Lahlef", "بن داود|Bendaoud", "غليزان|Relizane", "الحاسي|El Hassi", "سيدي أمحمد بن علي|Sidi M'hamed Benali", "مديونة|Mediouna", "بني زنطيس|Beni Zentis", "وادي الجمعة|Oued El Djemaa", "الحمادنة|El H'madna", "الرمكة|Ramka"]],
  ["49", "تيميمون", "Timimoun", "Timimoun", 1300, "5-8", ["تنركوك|Tinerkouk", "قصر قدور|Ksar Kaddour", "تيميمون|Timimoun", "أولاد السعيد|Ouled Said", "المطارفة|Metarfa", "أوقروت|Aougrout", "طالمين|Talmine", "شروين|Charouine", "أولاد عيسى|Ouled Aissa", "دلدول|Deldoul"]],
  ["50", "برج باجي مختار", "Bordj Badji Mokhtar", "Bordj Badji Mokhtar", 1500, "6-9", ["تيمياوين|Timiaouine", "برج باجي مختار|Bordj Badji Mokhtar"]],
  ["51", "أولاد جلال", "Ouled Djellal", "Ouled Djellal", 900, "4-6", ["رأس الميعاد|Ras El Miad", "بسباس|Besbes", "سيدي  خالد|Sidi Khaled", "الدوسن|Doucen", "أولاد جلال|Ouled Djellal", "الشعيبة|Chaiba"]],
  ["52", "بني عباس", "Beni Abbes", "Beni Abbes", 1400, "5-8", ["بني عباس|Beni-Abbes", "تامترت|Tamtert", "إقلي|Igli", "الواتة|El Ouata", "أولاد خضير|Ouled-Khodeir", "القصابي|Ksabi", "كرزاز|Kerzaz", "تيمودي|Timoudi", "بن يخلف|Beni-Ikhlef"]],
  ["53", "عين صالح", "In Salah", "In Salah", 1500, "6-9", ["إينغر|Inghar", "عين صالح|Ain Salah", "فقارة الزوى|Foggaret Ezzoua"]],
  ["54", "عين قزام", "In Guezzam", "In Guezzam", 1600, "7-10", ["تين زواتين|Tin Zouatine", "عين قزام|Ain Guezzam"]],
  ["55", "تقرت", "Touggourt", "Touggourt", 950, "4-7", ["تماسين|Temacine", "بلدة اعمر|Blidet Amor", "سيدي سليمان|Sidi Slimane", "المقارين|Megarine", "النزلة|Nezla", "تبسبست|Tebesbest", "تقرت|Touggourt", "الزاوية العابدية|Zaouia El Abidia", "الطيبات|Taibet", "بن ناصر|Benaceur", "المنقر|M'naguer", "العالية|El Alia", "الحجيرة|El-Hadjira"]],
  ["56", "جانت", "Djanet", "Djanet", 1600, "7-10", ["جانت|Djanet", "برج الحواس|Bordj El Haouass"]],
  ["57", "المغير", "El M'Ghair", "El M'Ghair", 950, "4-7", ["أم الطيور|Oum Touyour", "المغير|El-M'ghaier", "سطيل|Still", "سيدي خليل|Sidi Khelil", "سيدي عمران|Sidi Amrane", "المرارة|M'rara", "جامعة|Djamaa", "تندلة|Tenedla"]],
  ["58", "المنيعة", "El Meniaa", "El Meniaa", 1000, "4-7", ["المنيعة|El Meniaa", "حاسي القارة|Hassi Gara", "حاسي الفحل|Hassi Fehal"]],
  ["59", "أفلو", "Aflou", "Aflou", 900, "4-7", ["أفلو|Aflou", "سبقاق|Sebgag", "سيدي بوزيد|Sidi Bouzid", "بريدة|Brida", "الحاج المشري|Hadj Mechri", "تاويالة|Taouiala", "قلتة سيدي سعد|Gueltat Sidi Saad", "عين سيدي علي|Ain Sidi Ali", "البيضاء|El Beidha", "وادي مرة|Oued Morra", "وادي مزي|Oued M'Zi", "الغيشة|El Ghicha"]],
  ["60", "بريكة", "Barika", "Barika", 700, "3-5", ["بريكة|Barika", "بيطام|Bitam", "م دوكال|M’Doukal", "سقانة|Seggana", "تيلاطو|Tilatou", "عبد القادر عزيز|Abdelkader Azil", "جزار|Djezzar", "أولاد عمار|Ouled Ammar"]],
  ["61", "القنطرة", "El Kantara", "El Kantara", 800, "3-6", ["القنطرة|El Kantara", "عين زعطوط|Ain Zaatout", "برانيس|Branis", "الوتیة|El Outaya", "جمورة|Djemourah"]],
  ["62", "بئر العاتر", "Bir El Ater", "Bir El Ater", 750, "3-5", ["بئر العاتر|Bir El Ater", "نقرين|Negrine", "العقلة المالحة|El Ogla El Melha", "فركان|Ferkane"]],
  ["63", "العريشة", "El Aricha", "El Aricha", 750, "3-5", ["العريشة|El Aricha", "الگور|El Gor", "سيدي جيلالي|Sidi Djillali", "البويهي|El Bouihi"]],
  ["64", "قصر الشلالة", "Ksar Chellala", "Ksar Chellala", 750, "3-5", ["قصر الشلالة|Ksar Chellala", "زمالة الأمير عبد القادر|Zmalet El Emir Abdelkader", "حمادية|Hamadia", "الرشايقة|Rechaiga", "سرغين|Serguine", "بوغارة|Bougara"]],
  ["65", "عين وسارة", "Ain Oussara", "Ain Oussara", 800, "3-6", ["عين وسارة|Ain Ouessara", "الخميس|El Khemis", "البيرين|Birine", "بويرة الأحداب|Bouira Lahdab", "سيدي لخضر|Sidi Ladjel", "حاسي فدول|Hassi Fedoul", "عين فكة|Ain Fekka", "حاضرة|Had Sahary", "قرنيني|Guernini", "بنهار|Benhar"]],
  ["66", "مسعد", "Messaad", "Messaad", 800, "3-6", ["مسعد|Messaad", "سلمانة|Selmana", "دلدول|Deldoul", "فيض البطمة|Faidh El Botma", "أم العظام|Oum Laadham", "عمورة|Amourah", "سد الرحال|Sed Rahal", "قطارة|Guettara"]],
  ["67", "قصر البخاري", "Ksar El Boukhari", "Ksar El Boukhari", 600, "2-4", ["قصر البخاري|Ksar El Boukhari", "أولاد معرف|Ouled Maaref", "سيدي دامد|Sidi Damed", "عين بوسيف|Ain Boucif", "الكاف الأحمر|Kef Lakhdar", "عين اقصير|Ain Ouksir", "الدراق|Derrag", "بوطاط|Bouaiche", "شلالة العذاورة|Chelalet El Adhaoura", "بوغار|Boghar", "أولاد عنتر|Ouled Antar", "العوينات|El Ouinet", "عزيز|Aziz", "شهبونية|Chahbounia", "شنيقل|Cheniguel", "أم الجليل|Oum El Djallil", "مفاتحة|M’Fatha", "بوقزول|Boughezoul", "السناقصة|Saneg", "أولاد هلال|Ouled Hellal", "تفراوت|Tafraout"]],
  ["68", "بوسعادة", "Bou Saada", "Bou Saada", 700, "3-5", ["بوسعادة|Bou Saada", "أولاد سيدي ابراهيم|Ouled Sidi Brahim", "سيدي عامر|Sidi Ameur", "تامسة|Tamsa", "خوبانة|Khoubana", "مصيف|M’Cif", "أولاد سلامة|Ouled Slimane", "بن سرور|Ben Srour", "الحمادين|El Houamed", "الهامل|El Hamel", "الزرق|Zarzour", "محمد بودياف|Mouhamed Boudiaf", "بنزو|Benzouh", "بئر فضة|Bir Foda", "عين فارس|Ain Fares", "سيدي امحمد|Sidi M’Hamed", "مضاء|Menaa", "عين الملح|Ain El Meleh", "مدجيدل|Medjedel", "سليم|Slim", "عين الرش|Ain Errich", "أولتام|Oultem", "جبل مسعد|Djebel Messaad"]],
  ["69", "الأبيض سيدي الشيخ", "El Abiodh Sidi Cheikh", "El Abiodh Sidi Cheikh", 950, "4-6", ["الأبيض سيدي الشيخ|El Abiodh Sidi Cheikh", "عين العراك|Ain El Orak", "أربوات|Arbaouat", "البنود|El Bnoud", "بوسمغون|Boussemghoun", "الشلالة|Chellala", "المحرة|El Meharra"]],
];

export const WILAYA_SEED: WilayaSeed[] = RAW.map(([code, nameAr, nameFr, nameEn, fee, eta, communes]) => ({
  code,
  nameAr,
  nameFr,
  nameEn,
  fee,
  eta,
  communes: communes.map((c) => {
    const [ar, fr] = c.split("|");
    return { nameAr: ar, nameFr: fr, nameEn: fr };
  }),
}));

export const FREE_SHIPPING_THRESHOLD = 9000;
